//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battle
    {
        public Battle()
        {
            this.PlayerBattles = new HashSet<PlayerBattle>();
        }
    
        public int BattleId { get; set; }
        public long ArenaUniqueId { get; set; }
        public string ParserVersion { get; set; }
        public System.DateTime ArenaCreateTime { get; set; }
        public int ArenaTypeId { get; set; }
        public string ArenaTypeIcon { get; set; }
        public string ArenaTypeName { get; set; }
        public int BonusType { get; set; }
        public string BonusTypeName { get; set; }
        public double Duration { get; set; }
        public int FinishReason { get; set; }
        public string FinishReasonName { get; set; }
        public int GameplayId { get; set; }
        public string GameplayName { get; set; }
        public string Result { get; set; }
        public int WinnerTeam { get; set; }
        public int VehLockMode { get; set; }
    
        public virtual ICollection<PlayerBattle> PlayerBattles { get; set; }
    }
}
