//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClanDetail
    {
        public int ClanId { get; set; }
        public int PlayerId { get; set; }
        public System.DateTime AsOfDate { get; set; }
        public int ClanBattles { get; set; }
        public int AllBattles { get; set; }
        public int CompanyBattles { get; set; }
        public string Role { get; set; }
        public string Rolei18n { get; set; }
    
        public virtual Clan Clan { get; set; }
        public virtual Player Player { get; set; }
    }
}
