//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clan
    {
        public Clan()
        {
            this.ClanDetails = new HashSet<ClanDetail>();
        }
    
        public int ClanId { get; set; }
        public string Abbreviation { get; set; }
        public string Name { get; set; }
        public string EmblemLarge { get; set; }
        public string EmblemSmall { get; set; }
        public string EmblemBWTank { get; set; }
        public string EmblemMedium { get; set; }
        public System.DateTime CreatedAtDate { get; set; }
        public System.DateTime UpdatedAtDate { get; set; }
    
        public virtual ICollection<ClanDetail> ClanDetails { get; set; }
    }
}
