//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerBattle
    {
        public int PlayerId { get; set; }
        public int BattleId { get; set; }
        public int DamageDealt { get; set; }
        public int DamageReceived { get; set; }
        public string TankName { get; set; }
        public int XP { get; set; }
        public int XPPenalty { get; set; }
    
        public virtual Battle Battle { get; set; }
        public virtual Player Player { get; set; }
    }
}
