//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tank
    {
        public int TankId { get; set; }
        public string Nation { get; set; }
        public string Name { get; set; }
        public int Level { get; set; }
        public bool IsPremium { get; set; }
        public string Namei18n { get; set; }
        public string Nationi18n { get; set; }
        public string TankType { get; set; }
        public double ExpectedFrag { get; set; }
        public double ExpectedDamage { get; set; }
        public double ExpectedSpot { get; set; }
        public double ExpectedDefense { get; set; }
        public double ExpectedWin { get; set; }
    }
}
