//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WN8ExpectedTankValues
    {
        public string Name { get; set; }
        public double Frag { get; set; }
        public int Damage { get; set; }
        public double Spot { get; set; }
        public double Defense { get; set; }
        public double Win { get; set; }
        public int Tier { get; set; }
        public string Nation { get; set; }
        public string Class { get; set; }
        public int IDNum { get; set; }
    }
}
